AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: template-database-elecclean
Resources:
  DatabaseElecClean:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "PK"
          AttributeType: "S"
        - 
          AttributeName: "fraude"
          AttributeType: "N"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "fraudeGSI"
          KeySchema:
          - AttributeName: "fraude"
            KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
      KeySchema: 
        - AttributeName: "PK"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TableName: "ElecClean"
  
Outputs:
  TableStreamARN:
    Value: !GetAtt DatabaseElecClean.StreamArn
    Export:
      Name: "DatabaseStreamARN"